/** Recipe catalog — canonical recipe data for matching and dictionary search. */

import { WORLD_RECIPES } from './recipe-data-world.js';
import { WORLD_RECIPES_2 } from './recipe-data-world-2.js';
import { CHINA_RECIPES } from './recipe-data-china.js';

/** Broad cuisine groups for preference matching (e.g. "Asian" includes Thai, Korean, etc.). */
export const CUISINE_PREF_GROUPS = {
  asian: ['asian', 'thai', 'korean', 'japanese', 'vietnamese'],
  western: ['western', 'mexican'],
  mediterranean: ['mediterranean', 'middle-eastern'],
  comfort: ['comfort'],
};

/** Dictionary filter groups (e.g. "Western" includes Mexican). */
export const CUISINE_FILTER_GROUPS = {
  western: ['western', 'mexican'],
  mediterranean: ['mediterranean', 'middle-eastern'],
  comfort: ['comfort'],
};

export function matchesCuisineFilter(recipeCuisine, filter, { forPrefs = false } = {}) {
  if (filter === 'all' || filter === 'quick' || filter === 'vegetarian') return true;

  if (forPrefs) {
    const prefGroup = CUISINE_PREF_GROUPS[filter];
    if (prefGroup) return prefGroup.includes(recipeCuisine);
    return recipeCuisine === filter;
  }

  if (filter === 'asian') return recipeCuisine === 'asian';

  const filterGroup = CUISINE_FILTER_GROUPS[filter];
  if (filterGroup) return filterGroup.includes(recipeCuisine);
  return recipeCuisine === filter;
}

export const RECIPE_CATALOG = [
  // ── Original 10 recipes (migrated) ──────────────────────────────────────

  {
    id: 'garlic-butter-pasta',
    name: 'Garlic Butter Pasta',
    names: { 'zh-CN': '蒜香黄油意大利面', 'zh-TW': '蒜香奶油義大利麵' },
    aliases: ['蒜香面', 'garlic pasta', 'aglio e olio', '黄油意面'],
    tags: ['快手', '西式'],
    meal: ['lunch', 'dinner'],
    time: 'quick',
    difficulty: 'easy',
    diet: ['none', 'vegetarian'],
    cuisine: 'western',
    servings: 2,
    ingredients: ['pasta', 'garlic', 'butter', 'olive oil', 'cheese'],
    optional: ['basil', 'chili'],
    steps: [
      { instruction: 'Bring a large pot of salted water to a boil.', timer: 300 },
      { instruction: 'While water heats, mince 4 cloves of garlic finely.', timer: null },
      { instruction: 'Cook pasta according to package directions until al dente.', timer: 600 },
      { instruction: 'In a pan over medium heat, melt 3 tbsp butter with 1 tbsp olive oil. Add garlic and cook until fragrant — don\'t let it brown.', timer: 120 },
      { instruction: 'Drain pasta, reserving ½ cup pasta water. Toss pasta in the garlic butter, adding pasta water as needed for a silky sauce.', timer: 60 },
      { instruction: 'Season with salt and pepper. Top with grated cheese and serve immediately.', timer: null },
    ],
  },
  {
    id: 'chicken-stir-fry',
    name: 'Classic Chicken Stir-Fry',
    names: { 'zh-CN': '经典鸡肉小炒', 'zh-TW': '經典雞肉小炒' },
    aliases: ['鸡肉炒', 'chicken stir fry', '小炒鸡', '快手炒鸡'],
    tags: ['家常', '快手'],
    meal: ['lunch', 'dinner'],
    time: 'quick',
    difficulty: 'easy',
    diet: ['none', 'gluten-free', 'low-carb'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['chicken', 'garlic', 'ginger', 'soy sauce', 'bell pepper', 'onion', 'olive oil'],
    optional: ['broccoli', 'carrot', 'chili'],
    steps: [
      { instruction: 'Cut chicken into bite-sized pieces. Season with salt and pepper.', timer: null },
      { instruction: 'Prep vegetables: slice bell pepper and onion, mince garlic and ginger.', timer: 180 },
      { instruction: 'Heat 2 tbsp oil in a wok or large pan over high heat until shimmering.', timer: 60 },
      { instruction: 'Add chicken in a single layer. Sear without stirring for 2 minutes, then flip and cook through.', timer: 360 },
      { instruction: 'Push chicken to the side. Add garlic and ginger, stir 30 seconds, then add vegetables.', timer: 30 },
      { instruction: 'Stir-fry vegetables until crisp-tender, about 3–4 minutes.', timer: 240 },
      { instruction: 'Add 3 tbsp soy sauce, toss everything together, and serve over rice.', timer: 30 },
    ],
  },
  {
    id: 'veggie-fried-rice',
    name: 'Vegetable Fried Rice',
    names: { 'zh-CN': '蔬菜炒饭', 'zh-TW': '蔬菜炒飯' },
    aliases: ['素炒饭', 'fried rice', 'vegetable rice', '什锦炒饭'],
    tags: ['家常', '快手'],
    meal: ['lunch', 'dinner'],
    time: 'quick',
    difficulty: 'easy',
    diet: ['none', 'vegetarian'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['rice', 'eggs', 'onion', 'garlic', 'soy sauce', 'olive oil', 'carrot'],
    optional: ['peas', 'corn', 'bell pepper'],
    steps: [
      { instruction: 'If using fresh rice, spread it on a plate to cool. Cold or day-old rice works best.', timer: null },
      { instruction: 'Dice onion and carrot. Mince 2 cloves of garlic.', timer: 120 },
      { instruction: 'Beat 2 eggs with a pinch of salt.', timer: null },
      { instruction: 'Heat 1 tbsp oil in a wok over high heat. Scramble eggs, break into pieces, and set aside.', timer: 90 },
      { instruction: 'Add more oil, then onion and carrot. Stir-fry 2 minutes, add garlic.', timer: 120 },
      { instruction: 'Add rice, breaking up clumps. Stir-fry 3–4 minutes until heated through.', timer: 240 },
      { instruction: 'Return eggs, add 2 tbsp soy sauce, toss well, and serve.', timer: 30 },
    ],
  },
  {
    id: 'tomato-basil-pasta',
    name: 'Fresh Tomato Basil Pasta',
    names: { 'zh-CN': '新鲜番茄罗勒意大利面', 'zh-TW': '新鮮番茄羅勒義大利麵' },
    aliases: ['番茄意面', 'tomato pasta', '罗勒面', '地中海意面'],
    tags: ['西式', '素食'],
    meal: ['lunch', 'dinner'],
    time: 'medium',
    difficulty: 'easy',
    diet: ['none', 'vegetarian', 'vegan'],
    cuisine: 'mediterranean',
    servings: 2,
    ingredients: ['pasta', 'tomato', 'garlic', 'olive oil', 'basil'],
    optional: ['onion', 'chili'],
    steps: [
      { instruction: 'Bring salted water to a boil for pasta.', timer: 300 },
      { instruction: 'Dice 4 ripe tomatoes. Mince 3 cloves garlic. Tear fresh basil leaves.', timer: 180 },
      { instruction: 'Cook pasta until al dente. Reserve ½ cup pasta water before draining.', timer: 600 },
      { instruction: 'In a pan, warm 3 tbsp olive oil over medium heat. Add garlic, cook 1 minute.', timer: 60 },
      { instruction: 'Add tomatoes, season with salt, and simmer until they break down into a sauce.', timer: 600 },
      { instruction: 'Toss pasta with sauce and basil. Add pasta water to reach desired consistency.', timer: 60 },
      { instruction: 'Drizzle with olive oil and serve.', timer: null },
    ],
  },
  {
    id: 'creamy-mushroom-pasta',
    name: 'Creamy Mushroom Pasta',
    names: { 'zh-CN': '奶油蘑菇意大利面', 'zh-TW': '奶油蘑菇義大利麵' },
    aliases: ['蘑菇意面', 'mushroom pasta', '奶油面', '白酱意面'],
    tags: ['西式', 'comfort'],
    meal: ['lunch', 'dinner'],
    time: 'medium',
    difficulty: 'medium',
    diet: ['none', 'vegetarian'],
    cuisine: 'comfort',
    servings: 2,
    ingredients: ['pasta', 'mushroom', 'garlic', 'cream', 'butter', 'onion'],
    optional: ['cheese', 'basil'],
    steps: [
      { instruction: 'Slice mushrooms and dice onion. Mince 2 cloves garlic.', timer: 180 },
      { instruction: 'Boil salted water and cook pasta until al dente. Reserve ½ cup pasta water.', timer: 600 },
      { instruction: 'Melt 2 tbsp butter in a pan over medium-high heat. Sauté mushrooms until golden, about 5 minutes.', timer: 300 },
      { instruction: 'Add onion and garlic, cook until softened.', timer: 180 },
      { instruction: 'Pour in ½ cup cream, simmer gently for 3 minutes. Season with salt and pepper.', timer: 180 },
      { instruction: 'Toss drained pasta with sauce, thinning with pasta water if needed. Serve hot.', timer: 60 },
    ],
  },
  {
    id: 'shakshuka',
    name: 'Shakshuka (Eggs in Tomato Sauce)',
    names: { 'zh-CN': '北非蛋（番茄炖蛋）', 'zh-TW': '北非蛋（番茄燉蛋）' },
    aliases: ['番茄炖蛋', 'shakshuka', '北非蛋', '中东蛋'],
    tags: ['brunch', '地中海'],
    meal: ['breakfast', 'lunch', 'dinner'],
    time: 'medium',
    difficulty: 'medium',
    diet: ['none', 'vegetarian', 'gluten-free', 'low-carb'],
    cuisine: 'mediterranean',
    servings: 2,
    ingredients: ['eggs', 'tomato', 'onion', 'bell pepper', 'garlic', 'olive oil'],
    optional: ['chili', 'cilantro'],
    steps: [
      { instruction: 'Dice onion and bell pepper. Mince 3 cloves garlic.', timer: 180 },
      { instruction: 'Heat 2 tbsp olive oil in a skillet over medium heat. Sauté onion and pepper until soft, about 5 minutes.', timer: 300 },
      { instruction: 'Add garlic and 1 tsp cumin (optional). Cook 1 minute.', timer: 60 },
      { instruction: 'Add diced tomatoes (or 1 can). Simmer until sauce thickens, about 10 minutes.', timer: 600 },
      { instruction: 'Make 4 wells in the sauce and crack an egg into each. Cover and cook until whites set but yolks are runny.', timer: 360 },
      { instruction: 'Season with salt, pepper, and fresh herbs. Serve with bread for dipping.', timer: null },
    ],
  },
  {
    id: 'simple-omelette',
    name: 'Fluffy Cheese Omelette',
    names: { 'zh-CN': '蓬松芝士欧姆蛋', 'zh-TW': '蓬鬆起司歐姆蛋' },
    aliases: ['欧姆蛋', 'omelette', '芝士蛋', '煎蛋卷'],
    tags: ['早餐', '快手'],
    meal: ['breakfast', 'snack'],
    time: 'quick',
    difficulty: 'easy',
    diet: ['none', 'vegetarian', 'gluten-free', 'low-carb'],
    cuisine: 'western',
    servings: 1,
    ingredients: ['eggs', 'butter', 'cheese'],
    optional: ['mushroom', 'spinach', 'onion'],
    steps: [
      { instruction: 'Beat 3 eggs with a pinch of salt until uniform.', timer: null },
      { instruction: 'Grate or slice cheese. Prep any add-ins (mushrooms, spinach) if using.', timer: 60 },
      { instruction: 'Melt 1 tbsp butter in a non-stick pan over medium-low heat.', timer: 30 },
      { instruction: 'Pour in eggs. As they set, gently push cooked edges toward center, tilting pan.', timer: 180 },
      { instruction: 'When mostly set but still slightly wet on top, add cheese to one half.', timer: null },
      { instruction: 'Fold omelette in half. Cook 30 seconds more, then slide onto a plate.', timer: 30 },
    ],
  },
  {
    id: 'tofu-coconut-curry',
    name: 'Tofu Coconut Curry',
    names: { 'zh-CN': '豆腐椰浆咖喱', 'zh-TW': '豆腐椰漿咖哩' },
    aliases: ['椰浆咖喱', 'coconut curry', '豆腐咖喱', '泰式咖喱'],
    tags: ['素食', '亚洲'],
    meal: ['lunch', 'dinner'],
    time: 'medium',
    difficulty: 'medium',
    diet: ['none', 'vegetarian', 'vegan', 'gluten-free'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['tofu', 'coconut milk', 'onion', 'garlic', 'ginger', 'bell pepper'],
    optional: ['spinach', 'carrot', 'rice'],
    steps: [
      { instruction: 'Press tofu and cut into cubes. Dice onion, mince garlic and ginger.', timer: 300 },
      { instruction: 'Heat oil in a pot. Pan-fry tofu cubes until golden on all sides. Set aside.', timer: 360 },
      { instruction: 'In the same pot, sauté onion until translucent. Add garlic and ginger, cook 1 minute.', timer: 240 },
      { instruction: 'Add 1 can coconut milk and 1 tbsp curry powder (or paste). Simmer 5 minutes.', timer: 300 },
      { instruction: 'Add bell pepper and return tofu. Simmer until peppers are tender.', timer: 360 },
      { instruction: 'Season with salt and lime juice. Serve over rice.', timer: null },
    ],
  },
  {
    id: 'roasted-potatoes',
    name: 'Crispy Roasted Potatoes',
    names: { 'zh-CN': '香脆烤土豆', 'zh-TW': '香脆烤馬鈴薯' },
    aliases: ['烤土豆', 'roasted potatoes', '烤箱土豆', '薯角'],
    tags: ['side', 'comfort'],
    meal: ['lunch', 'dinner', 'snack'],
    time: 'medium',
    difficulty: 'easy',
    diet: ['none', 'vegetarian', 'vegan', 'gluten-free'],
    cuisine: 'comfort',
    servings: 2,
    ingredients: ['potato', 'olive oil', 'garlic'],
    optional: ['rosemary', 'onion'],
    steps: [
      { instruction: 'Preheat oven to 220°C (425°F).', timer: 600 },
      { instruction: 'Cut potatoes into 2 cm chunks. Soak in cold water 10 minutes, then drain and pat dry.', timer: 600 },
      { instruction: 'Toss potatoes with 2 tbsp olive oil, salt, and minced garlic.', timer: 60 },
      { instruction: 'Spread on a baking sheet in a single layer. Roast 25–30 minutes, flipping halfway.', timer: 1500 },
      { instruction: 'Potatoes are done when golden and crisp outside, fluffy inside. Season and serve.', timer: null },
    ],
  },
  {
    id: 'beef-tacos',
    name: 'Quick Beef Tacos',
    names: { 'zh-CN': '快手牛肉塔可', 'zh-TW': '快手牛肉塔可' },
    aliases: ['塔可', 'tacos', '墨西哥卷', 'beef tacos'],
    tags: ['西式', '快手'],
    meal: ['lunch', 'dinner'],
    time: 'quick',
    difficulty: 'easy',
    diet: ['none', 'gluten-free'],
    cuisine: 'comfort',
    servings: 4,
    ingredients: ['beef', 'onion', 'tomato', 'cheese'],
    optional: ['avocado', 'chili', 'cilantro'],
    steps: [
      { instruction: 'Dice onion and tomato. Shred cheese. Warm tortillas if you have them.', timer: 180 },
      { instruction: 'Brown ground beef in a skillet over medium-high heat, breaking it up as it cooks.', timer: 480 },
      { instruction: 'Drain excess fat. Add onion and cook until softened.', timer: 180 },
      { instruction: 'Season with 1 tbsp taco seasoning (or cumin, chili powder, salt). Add a splash of water and simmer 2 minutes.', timer: 120 },
      { instruction: 'Fill tortillas with beef, top with tomato and cheese. Add avocado and cilantro if available.', timer: null },
    ],
  },

  // ── Chinese home-cooking (小红书 style) ─────────────────────────────────

  {
    id: 'tomato-scrambled-eggs',
    name: 'Tomato Scrambled Eggs',
    names: { 'zh-CN': '番茄炒蛋', 'zh-TW': '番茄炒蛋' },
    aliases: ['西红柿炒蛋', '番茄蛋', 'tomato eggs', '国民菜'],
    tags: ['家常', '小红书', '快手'],
    meal: ['lunch', 'dinner', 'breakfast'],
    time: 'quick',
    difficulty: 'easy',
    diet: ['none', 'vegetarian', 'gluten-free'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['eggs', 'tomato', 'onion', 'garlic', 'soy sauce', 'sugar', 'olive oil'],
    optional: ['cilantro'],
    steps: [
      { instruction: 'Cut tomatoes into wedges. Beat 3 eggs with a pinch of salt and 1 tsp sugar.', timer: 120 },
      { instruction: 'Heat 2 tbsp oil in a wok over high heat. Pour in eggs, scramble until just set, and remove.', timer: 90 },
      { instruction: 'Add a little more oil. Sauté minced garlic and onion until fragrant, about 30 seconds.', timer: 30 },
      { instruction: 'Add tomatoes, 1 tbsp soy sauce, and a pinch of sugar. Cook until tomatoes soften and release juice.', timer: 180 },
      { instruction: 'Return scrambled eggs, gently fold together. Taste and adjust seasoning. Serve hot with rice.', timer: 30 },
    ],
  },
  {
    id: 'red-braised-pork',
    name: 'Red-Braised Pork',
    names: { 'zh-CN': '红烧肉', 'zh-TW': '紅燒肉' },
    aliases: ['东坡肉', 'braised pork belly', '本帮红烧肉', '小红书红烧肉'],
    tags: ['家常', '小红书', '硬菜'],
    meal: ['lunch', 'dinner'],
    time: 'leisurely',
    difficulty: 'medium',
    diet: ['none'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['pork', 'soy sauce', 'sugar', 'ginger', 'garlic', 'onion'],
    optional: ['eggs'],
    steps: [
      { instruction: 'Cut pork belly into 3 cm cubes. Blanch in boiling water 2 minutes, drain and rinse.', timer: 180 },
      { instruction: 'In a pot, melt 2 tbsp sugar with a splash of water over medium heat until amber (careful not to burn).', timer: 180 },
      { instruction: 'Add pork, ginger slices, and garlic. Stir to coat with caramel, about 2 minutes.', timer: 120 },
      { instruction: 'Add 3 tbsp soy sauce and enough water to barely cover. Bring to a boil, then reduce to low simmer.', timer: 60 },
      { instruction: 'Cover and braise 45–60 minutes until pork is tender and sauce is glossy. Stir occasionally.', timer: 2700 },
      { instruction: 'Uncover, raise heat slightly, and reduce sauce until thick and clinging. Serve with rice.', timer: 300 },
    ],
  },
  {
    id: 'kung-pao-chicken',
    name: 'Kung Pao Chicken',
    names: { 'zh-CN': '宫保鸡丁', 'zh-TW': '宮保雞丁' },
    aliases: ['宫保', 'kung pao', '花生鸡丁', '川菜'],
    tags: ['家常', '小红书', '川菜'],
    meal: ['lunch', 'dinner'],
    time: 'medium',
    difficulty: 'medium',
    diet: ['none'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['chicken', 'peanuts', 'bell pepper', 'chili', 'garlic', 'ginger', 'soy sauce', 'vinegar', 'sugar', 'olive oil'],
    optional: ['onion'],
    steps: [
      { instruction: 'Dice chicken into 1.5 cm cubes. Marinate with 1 tbsp soy sauce and 1 tsp sugar for 10 minutes.', timer: 600 },
      { instruction: 'Mix sauce: 2 tbsp soy sauce, 1 tbsp vinegar, 1 tsp sugar, and 2 tbsp water. Prep diced bell pepper, minced garlic and ginger.', timer: 120 },
      { instruction: 'Heat 2 tbsp oil in a wok over high heat. Stir-fry chicken until just cooked through. Remove and set aside.', timer: 240 },
      { instruction: 'Add dried chilies (optional), garlic, and ginger. Stir 15 seconds until fragrant.', timer: 15 },
      { instruction: 'Add bell pepper, stir-fry 1 minute. Return chicken, pour in sauce, toss until coated.', timer: 90 },
      { instruction: 'Add roasted peanuts, toss once more, and serve immediately with rice.', timer: 30 },
    ],
  },
  {
    id: 'twice-cooked-pork',
    name: 'Twice-Cooked Pork',
    names: { 'zh-CN': '回锅肉', 'zh-TW': '回鍋肉' },
    aliases: ['回锅', 'twice cooked pork', '川菜回锅肉', '蒜苗回锅肉'],
    tags: ['家常', '小红书', '川菜'],
    meal: ['lunch', 'dinner'],
    time: 'medium',
    difficulty: 'medium',
    diet: ['none'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['pork', 'bell pepper', 'onion', 'garlic', 'ginger', 'soy sauce', 'chili', 'olive oil'],
    optional: ['cilantro'],
    steps: [
      { instruction: 'Simmer pork belly in water with ginger slices for 20 minutes until just cooked. Cool and slice thin.', timer: 1200 },
      { instruction: 'Slice bell pepper and onion. Mince garlic. Mix 2 tbsp soy sauce with 1 tsp sugar for the sauce.', timer: 120 },
      { instruction: 'Heat a dry wok over medium-high. Fry pork slices until edges curl and fat renders, about 3 minutes.', timer: 180 },
      { instruction: 'Push pork aside, add 1 tbsp chili bean paste (doubanjiang) if available, or chili and garlic. Stir 30 seconds.', timer: 30 },
      { instruction: 'Add bell pepper and onion. Stir-fry 2 minutes until crisp-tender.', timer: 120 },
      { instruction: 'Pour in sauce, toss everything together, and serve with rice.', timer: 30 },
    ],
  },
  {
    id: 'sweet-sour-pork-ribs',
    name: 'Sweet and Sour Pork Ribs',
    names: { 'zh-CN': '糖醋排骨', 'zh-TW': '糖醋排骨' },
    aliases: ['糖醋', 'sweet sour ribs', '排骨', '小红书排骨'],
    tags: ['家常', '小红书'],
    meal: ['lunch', 'dinner'],
    time: 'medium',
    difficulty: 'medium',
    diet: ['none'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['pork', 'vinegar', 'sugar', 'soy sauce', 'garlic', 'ginger', 'olive oil'],
    optional: ['onion'],
    steps: [
      { instruction: 'Cut pork ribs into bite-sized pieces. Pat dry and season lightly with salt.', timer: 180 },
      { instruction: 'Heat 2 tbsp oil in a wok. Sear ribs on all sides until golden brown, about 5 minutes.', timer: 300 },
      { instruction: 'Add minced garlic and ginger, stir 30 seconds. Add 2 tbsp soy sauce and 1 cup water.', timer: 30 },
      { instruction: 'Cover and simmer on low for 25 minutes until ribs are tender.', timer: 1500 },
      { instruction: 'Mix 3 tbsp sugar and 2 tbsp vinegar. Add to pot, uncover, and reduce until sauce is sticky and glossy.', timer: 300 },
      { instruction: 'Toss ribs to coat evenly. Serve hot.', timer: null },
    ],
  },
  {
    id: 'cola-chicken-wings',
    name: 'Cola Chicken Wings',
    names: { 'zh-CN': '可乐鸡翅', 'zh-TW': '可樂雞翅' },
    aliases: ['可乐鸡', 'cola chicken', '鸡翅', '小红书鸡翅'],
    tags: ['家常', '小红书', '网红菜'],
    meal: ['lunch', 'dinner'],
    time: 'medium',
    difficulty: 'easy',
    diet: ['none'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['chicken', 'soy sauce', 'sugar', 'ginger', 'garlic', 'olive oil'],
    optional: ['onion'],
    steps: [
      { instruction: 'Score chicken wings lightly. Pat dry. Mince ginger and garlic.', timer: 120 },
      { instruction: 'Heat 1 tbsp oil in a pan. Sear wings skin-side down until golden, about 4 minutes per side.', timer: 480 },
      { instruction: 'Add ginger and garlic, stir 30 seconds. Pour in 1 can cola (about 330 ml) and 2 tbsp soy sauce.', timer: 30 },
      { instruction: 'Bring to a boil, then simmer uncovered, turning occasionally, for 15 minutes.', timer: 900 },
      { instruction: 'When sauce reduces by half, add 1 tsp sugar. Increase heat and glaze wings until sticky and caramelized.', timer: 180 },
      { instruction: 'Serve immediately — the sauce should coat the wings beautifully.', timer: null },
    ],
  },
  {
    id: 'mapo-tofu',
    name: 'Mapo Tofu',
    names: { 'zh-CN': '麻婆豆腐', 'zh-TW': '麻婆豆腐' },
    aliases: ['麻婆', 'mapo tofu', '川菜豆腐', '花椒豆腐'],
    tags: ['家常', '小红书', '川菜'],
    meal: ['lunch', 'dinner'],
    time: 'quick',
    difficulty: 'medium',
    diet: ['none'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['tofu', 'pork', 'chili', 'garlic', 'ginger', 'soy sauce', 'olive oil'],
    optional: ['onion', 'cilantro'],
    steps: [
      { instruction: 'Cut soft tofu into 2 cm cubes. Mince pork. Mince garlic and ginger.', timer: 180 },
      { instruction: 'Blanch tofu in salted boiling water 1 minute. Drain gently and set aside.', timer: 60 },
      { instruction: 'Heat 2 tbsp oil in a wok. Brown minced pork, breaking it up, about 2 minutes.', timer: 120 },
      { instruction: 'Add chili bean paste (doubanjiang) or chili, garlic, and ginger. Stir-fry until fragrant, 30 seconds.', timer: 30 },
      { instruction: 'Add ½ cup water and 1 tbsp soy sauce. Gently slide in tofu. Simmer 3 minutes without stirring too much.', timer: 180 },
      { instruction: 'Thicken with cornstarch slurry (1 tsp cornstarch + 2 tbsp water). Drizzle with chili oil if desired. Serve over rice.', timer: 60 },
    ],
  },
  {
    id: 'fish-fragrant-pork',
    name: 'Fish-Fragrant Shredded Pork',
    names: { 'zh-CN': '鱼香肉丝', 'zh-TW': '魚香肉絲' },
    aliases: ['鱼香', 'yu xiang', '鱼香肉', '川菜经典'],
    tags: ['家常', '小红书', '川菜'],
    meal: ['lunch', 'dinner'],
    time: 'quick',
    difficulty: 'medium',
    diet: ['none'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['pork', 'carrot', 'bell pepper', 'garlic', 'ginger', 'soy sauce', 'vinegar', 'sugar', 'chili', 'olive oil'],
    optional: ['onion'],
    steps: [
      { instruction: 'Julienne pork, carrot, and bell pepper into thin matchsticks. Mince garlic and ginger.', timer: 240 },
      { instruction: 'Mix fish-fragrant sauce: 2 tbsp soy sauce, 1 tbsp vinegar, 1 tbsp sugar, 1 tsp chili, and 2 tbsp water.', timer: null },
      { instruction: 'Marinate pork with 1 tsp soy sauce for 5 minutes.', timer: 300 },
      { instruction: 'Heat 2 tbsp oil in a wok over high heat. Stir-fry pork until just cooked. Remove.', timer: 180 },
      { instruction: 'Add carrot and bell pepper, stir-fry 2 minutes. Add garlic, ginger, and chili, stir 15 seconds.', timer: 135 },
      { instruction: 'Return pork, pour in sauce, toss quickly until everything is coated. Serve with rice.', timer: 60 },
    ],
  },
  {
    id: 'hot-sour-potato-shreds',
    name: 'Hot and Sour Potato Shreds',
    names: { 'zh-CN': '酸辣土豆丝', 'zh-TW': '酸辣土豆絲' },
    aliases: ['土豆丝', 'potato shreds', '酸辣土豆', '快手小炒'],
    tags: ['家常', '小红书', '快手'],
    meal: ['lunch', 'dinner'],
    time: 'quick',
    difficulty: 'easy',
    diet: ['none', 'vegetarian', 'vegan', 'gluten-free'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['potato', 'chili', 'vinegar', 'garlic', 'olive oil'],
    optional: ['onion', 'cilantro'],
    steps: [
      { instruction: 'Peel potato and julienne into thin matchsticks. Rinse in cold water until water runs clear, then drain well.', timer: 240 },
      { instruction: 'Mince garlic and slice fresh or dried chilies.', timer: 60 },
      { instruction: 'Heat 2 tbsp oil in a wok over high heat until smoking. Add chilies and garlic, stir 10 seconds.', timer: 10 },
      { instruction: 'Add potato shreds all at once. Stir-fry vigorously on high heat for 2–3 minutes — keep them moving.', timer: 180 },
      { instruction: 'Add 2 tbsp vinegar along the side of the wok (creates a burst of aroma). Season with salt.', timer: 30 },
      { instruction: 'Potatoes should be crisp-tender, not mushy. Serve immediately.', timer: null },
    ],
  },
  {
    id: 'braised-eggplant',
    name: 'Braised Eggplant',
    names: { 'zh-CN': '红烧茄子', 'zh-TW': '紅燒茄子' },
    aliases: ['茄子', 'braised eggplant', '烧茄子', '下饭菜'],
    tags: ['家常', '小红书', '素食'],
    meal: ['lunch', 'dinner'],
    time: 'medium',
    difficulty: 'easy',
    diet: ['none', 'vegetarian', 'vegan'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['eggplant', 'garlic', 'soy sauce', 'sugar', 'ginger', 'olive oil'],
    optional: ['onion', 'chili'],
    steps: [
      { instruction: 'Cut eggplant into finger-sized strips. Soak in salted water 5 minutes, drain and pat dry.', timer: 300 },
      { instruction: 'Heat 3 tbsp oil in a wok. Fry eggplant in batches until golden and soft, about 4 minutes. Set aside.', timer: 240 },
      { instruction: 'Leave 1 tbsp oil in wok. Sauté minced garlic and ginger until fragrant.', timer: 30 },
      { instruction: 'Return eggplant. Add 2 tbsp soy sauce, 1 tsp sugar, and 3 tbsp water.', timer: null },
      { instruction: 'Simmer 3 minutes, tossing gently, until sauce coats the eggplant and it\'s silky tender.', timer: 180 },
      { instruction: 'Garnish with scallions if available. Serve with rice.', timer: null },
    ],
  },
  {
    id: 'garlic-broccoli',
    name: 'Garlic Broccoli',
    names: { 'zh-CN': '蒜蓉西兰花', 'zh-TW': '蒜蓉西蘭花' },
    aliases: ['蒜蓉西蓝花', 'garlic broccoli', '清炒西兰花', '健康菜'],
    tags: ['家常', '小红书', '健康'],
    meal: ['lunch', 'dinner'],
    time: 'quick',
    difficulty: 'easy',
    diet: ['none', 'vegetarian', 'vegan', 'gluten-free', 'low-carb'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['broccoli', 'garlic', 'soy sauce', 'olive oil'],
    optional: ['chili'],
    steps: [
      { instruction: 'Cut broccoli into small florets. Mince 4 cloves garlic.', timer: 120 },
      { instruction: 'Blanch broccoli in boiling salted water 2 minutes until bright green. Drain and shock in cold water.', timer: 120 },
      { instruction: 'Heat 2 tbsp oil in a wok over high heat. Add garlic, stir until golden and fragrant, about 30 seconds.', timer: 30 },
      { instruction: 'Add broccoli, toss quickly on high heat for 1 minute.', timer: 60 },
      { instruction: 'Season with 1 tbsp soy sauce and a pinch of salt. Toss and serve.', timer: 30 },
    ],
  },
  {
    id: 'di-san-xian',
    name: 'Di San Xian (Three Earth Delights)',
    names: { 'zh-CN': '地三鲜', 'zh-TW': '地三鮮' },
    aliases: ['地三鲜', '东北地三鲜', 'three delights', '土豆茄子青椒'],
    tags: ['家常', '小红书', '东北菜'],
    meal: ['lunch', 'dinner'],
    time: 'medium',
    difficulty: 'medium',
    diet: ['none', 'vegetarian', 'vegan'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['potato', 'eggplant', 'bell pepper', 'garlic', 'soy sauce', 'sugar', 'olive oil'],
    optional: ['ginger'],
    steps: [
      { instruction: 'Cut potato, eggplant, and bell pepper into bite-sized chunks. Mince garlic.', timer: 240 },
      { instruction: 'Fry potato pieces in oil until golden and cooked through, about 5 minutes. Drain and set aside.', timer: 300 },
      { instruction: 'Fry eggplant until soft and golden, about 4 minutes. Drain and set aside.', timer: 240 },
      { instruction: 'Leave 1 tbsp oil, stir-fry bell pepper 1 minute. Add garlic, stir 15 seconds.', timer: 75 },
      { instruction: 'Return potato and eggplant. Add 2 tbsp soy sauce, 1 tsp sugar, and 2 tbsp water. Toss to coat.', timer: 120 },
      { instruction: 'Simmer briefly until everything is glossy and well combined. Serve with rice.', timer: 60 },
    ],
  },
  {
    id: 'bell-pepper-pork',
    name: 'Shredded Pork with Bell Pepper',
    names: { 'zh-CN': '青椒肉丝', 'zh-TW': '青椒肉絲' },
    aliases: ['青椒炒肉', 'bell pepper pork', '肉丝', '下饭菜'],
    tags: ['家常', '小红书', '快手'],
    meal: ['lunch', 'dinner'],
    time: 'quick',
    difficulty: 'easy',
    diet: ['none'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['pork', 'bell pepper', 'garlic', 'ginger', 'soy sauce', 'olive oil'],
    optional: ['onion'],
    steps: [
      { instruction: 'Julienne pork and bell pepper into thin strips. Mince garlic and ginger.', timer: 180 },
      { instruction: 'Marinate pork with 1 tbsp soy sauce for 5 minutes.', timer: 300 },
      { instruction: 'Heat 2 tbsp oil in a wok over high heat. Stir-fry pork until just cooked. Remove.', timer: 180 },
      { instruction: 'Add bell pepper, stir-fry 1 minute until crisp-tender.', timer: 60 },
      { instruction: 'Return pork, add garlic and ginger, stir 30 seconds. Season with 1 tbsp soy sauce.', timer: 30 },
      { instruction: 'Toss everything together and serve with rice.', timer: null },
    ],
  },
  {
    id: 'yangzhou-fried-rice',
    name: 'Yangzhou Fried Rice',
    names: { 'zh-CN': '扬州炒饭', 'zh-TW': '揚州炒飯' },
    aliases: ['扬州蛋炒饭', 'yangzhou rice', '什锦炒饭', '经典炒饭'],
    tags: ['家常', '小红书'],
    meal: ['lunch', 'dinner'],
    time: 'quick',
    difficulty: 'medium',
    diet: ['none'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['rice', 'eggs', 'shrimp', 'peas', 'carrot', 'onion', 'garlic', 'soy sauce', 'olive oil'],
    optional: ['corn'],
    steps: [
      { instruction: 'Use cold day-old rice. Dice carrot and onion. Beat 2 eggs. Prep shrimp (peeled if needed).', timer: 240 },
      { instruction: 'Heat 1 tbsp oil, scramble eggs lightly, break into pieces, and set aside.', timer: 90 },
      { instruction: 'Add more oil, stir-fry shrimp until pink, about 1 minute. Remove.', timer: 60 },
      { instruction: 'Stir-fry onion, carrot, and peas 2 minutes. Add minced garlic.', timer: 120 },
      { instruction: 'Add rice, breaking up clumps. Stir-fry on high heat 3 minutes.', timer: 180 },
      { instruction: 'Return eggs and shrimp, add 2 tbsp soy sauce, toss well. Serve hot.', timer: 30 },
    ],
  },
  {
    id: 'egg-fried-rice',
    name: 'Classic Egg Fried Rice',
    names: { 'zh-CN': '蛋炒饭', 'zh-TW': '蛋炒飯' },
    aliases: ['鸡蛋炒饭', 'egg fried rice', '黄金炒饭', '隔夜饭'],
    tags: ['家常', '小红书', '快手'],
    meal: ['lunch', 'dinner'],
    time: 'quick',
    difficulty: 'easy',
    diet: ['none'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['rice', 'eggs', 'onion', 'soy sauce', 'olive oil'],
    optional: ['peas', 'carrot', 'green beans'],
    steps: [
      { instruction: 'Use cold leftover rice — spread clumps apart with your hands. Dice onion finely.', timer: 120 },
      { instruction: 'Beat 2 eggs with a pinch of salt.', timer: null },
      { instruction: 'Heat 2 tbsp oil in a wok over high heat. Pour in eggs, scramble quickly, break into small pieces.', timer: 60 },
      { instruction: 'Push eggs aside, add onion, stir 30 seconds. Add rice all at once.', timer: 30 },
      { instruction: 'Stir-fry vigorously 3–4 minutes until rice is separated and lightly golden.', timer: 240 },
      { instruction: 'Add 2 tbsp soy sauce around the edge of the wok. Toss and serve immediately.', timer: 30 },
    ],
  },
  {
    id: 'scallion-oil-noodles',
    name: 'Scallion Oil Noodles',
    names: { 'zh-CN': '葱油拌面', 'zh-TW': '蔥油拌麵' },
    aliases: ['葱油面', 'scallion noodles', '上海葱油面', '拌面'],
    tags: ['家常', '小红书', '快手'],
    meal: ['lunch', 'dinner', 'breakfast'],
    time: 'quick',
    difficulty: 'easy',
    diet: ['none', 'vegetarian'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['noodles', 'onion', 'soy sauce', 'sugar', 'olive oil'],
    optional: ['garlic'],
    steps: [
      { instruction: 'Slice a generous amount of green onion (or use onion sliced thin). Mix 3 tbsp soy sauce with 1 tsp sugar.', timer: 120 },
      { instruction: 'Heat 4 tbsp oil in a small pot over medium-low. Add scallions/onion, cook slowly until deeply golden, about 8 minutes.', timer: 480 },
      { instruction: 'Boil noodles according to package until al dente. Reserve 2 tbsp cooking water.', timer: 360 },
      { instruction: 'Drain noodles, toss with scallion oil and soy-sugar mixture.', timer: 30 },
      { instruction: 'Add reserved noodle water if needed for a silky coating. Serve immediately.', timer: null },
    ],
  },
  {
    id: 'steamed-fish',
    name: 'Steamed Fish',
    names: { 'zh-CN': '清蒸鱼', 'zh-TW': '清蒸魚' },
    aliases: ['蒸鱼', 'steamed fish', '粤式蒸鱼', '健康鱼'],
    tags: ['家常', '小红书', '健康'],
    meal: ['lunch', 'dinner'],
    time: 'medium',
    difficulty: 'medium',
    diet: ['none', 'gluten-free', 'low-carb'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['fish', 'ginger', 'soy sauce', 'onion', 'olive oil'],
    optional: ['cilantro'],
    steps: [
      { instruction: 'Clean fish and score both sides. Place ginger slices inside and on top. Let sit 5 minutes.', timer: 300 },
      { instruction: 'Set up steamer and bring water to a rolling boil.', timer: 300 },
      { instruction: 'Steam fish on a plate over high heat. A 500 g whole fish takes about 8–10 minutes.', timer: 600 },
      { instruction: 'Fish is done when flesh flakes easily at the thickest part. Discard steaming liquid.', timer: null },
      { instruction: 'Top with fresh ginger shreds and sliced scallion. Drizzle hot oil over aromatics to release fragrance.', timer: 30 },
      { instruction: 'Finish with 2 tbsp soy sauce around the fish. Serve immediately.', timer: null },
    ],
  },
  {
    id: 'braised-tofu',
    name: 'Braised Tofu',
    names: { 'zh-CN': '红烧豆腐', 'zh-TW': '紅燒豆腐' },
    aliases: ['烧豆腐', 'braised tofu', '家常豆腐', '下饭菜'],
    tags: ['家常', '小红书', '素食'],
    meal: ['lunch', 'dinner'],
    time: 'medium',
    difficulty: 'easy',
    diet: ['none', 'vegetarian', 'vegan'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['tofu', 'soy sauce', 'sugar', 'garlic', 'ginger', 'onion', 'olive oil'],
    optional: ['chili'],
    steps: [
      { instruction: 'Cut firm tofu into 2 cm cubes. Pat dry. Mince garlic and ginger, dice onion.', timer: 180 },
      { instruction: 'Heat 3 tbsp oil in a pan. Pan-fry tofu until golden on all sides, about 3 minutes per batch.', timer: 360 },
      { instruction: 'Remove excess oil. Sauté onion, garlic, and ginger until fragrant.', timer: 60 },
      { instruction: 'Return tofu. Add 3 tbsp soy sauce, 1 tsp sugar, and ½ cup water.', timer: null },
      { instruction: 'Simmer covered 5 minutes until sauce reduces and tofu absorbs flavor.', timer: 300 },
      { instruction: 'Uncover, reduce sauce until glossy. Serve with rice.', timer: 120 },
    ],
  },
  {
    id: 'curry-chicken',
    name: 'Curry Chicken',
    names: { 'zh-CN': '咖喱鸡', 'zh-TW': '咖哩雞' },
    aliases: ['咖喱', 'curry chicken', '土豆咖喱鸡', '港式咖喱'],
    tags: ['家常', '小红书'],
    meal: ['lunch', 'dinner'],
    time: 'medium',
    difficulty: 'easy',
    diet: ['none', 'gluten-free'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['chicken', 'potato', 'onion', 'carrot', 'coconut milk', 'garlic', 'ginger', 'olive oil'],
    optional: ['rice'],
    steps: [
      { instruction: 'Cut chicken into bite-sized pieces. Dice potato, carrot, and onion. Mince garlic and ginger.', timer: 240 },
      { instruction: 'Heat 2 tbsp oil in a pot. Brown chicken pieces on all sides, about 4 minutes. Remove.', timer: 240 },
      { instruction: 'Sauté onion until soft. Add garlic, ginger, and 2 tbsp curry powder or paste. Stir 1 minute.', timer: 120 },
      { instruction: 'Add potato and carrot, stir to coat. Return chicken.', timer: 60 },
      { instruction: 'Pour in 1 cup coconut milk and ½ cup water. Simmer 20 minutes until chicken and vegetables are tender.', timer: 1200 },
      { instruction: 'Season with salt. Serve over rice.', timer: null },
    ],
  },
  {
    id: 'smashed-cucumber',
    name: 'Smashed Cucumber Salad',
    names: { 'zh-CN': '拍黄瓜', 'zh-TW': '拍黃瓜' },
    aliases: ['拍青瓜', 'smashed cucumber', '凉拌黄瓜', '凉菜'],
    tags: ['家常', '小红书', '凉菜'],
    meal: ['lunch', 'dinner', 'snack'],
    time: 'quick',
    difficulty: 'easy',
    diet: ['none', 'vegetarian', 'vegan', 'gluten-free', 'low-carb'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['cucumber', 'garlic', 'vinegar', 'soy sauce', 'sugar', 'chili'],
    optional: ['cilantro'],
    steps: [
      { instruction: 'Place cucumbers on a cutting board. Smash with the flat side of a knife, then cut into irregular chunks.', timer: 120 },
      { instruction: 'Toss with 1 tsp salt and let sit 5 minutes. Drain excess water.', timer: 300 },
      { instruction: 'Mince garlic finely. Mix dressing: 2 tbsp vinegar, 1 tbsp soy sauce, 1 tsp sugar.', timer: 60 },
      { instruction: 'Pour dressing over cucumber. Add garlic and sliced chili.', timer: null },
      { instruction: 'Toss well and chill 10 minutes before serving for best flavor.', timer: 600 },
    ],
  },
  {
    id: 'ants-climbing-tree',
    name: 'Ants Climbing a Tree',
    names: { 'zh-CN': '蚂蚁上树', 'zh-TW': '螞蟻上樹' },
    aliases: ['蚂蚁上树', 'ants climbing tree', '粉丝肉末', '川菜'],
    tags: ['家常', '小红书', '川菜'],
    meal: ['lunch', 'dinner'],
    time: 'quick',
    difficulty: 'medium',
    diet: ['none'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['pork', 'noodles', 'garlic', 'ginger', 'soy sauce', 'chili', 'olive oil'],
    optional: ['onion'],
    steps: [
      { instruction: 'Soak glass noodles (vermicelli) in warm water 10 minutes until soft. Drain and cut shorter.', timer: 600 },
      { instruction: 'Mince pork finely. Mince garlic and ginger.', timer: 120 },
      { instruction: 'Heat 2 tbsp oil in a wok. Brown minced pork, breaking it up, until crispy bits form.', timer: 180 },
      { instruction: 'Add chili bean paste (or chili), garlic, and ginger. Stir 30 seconds.', timer: 30 },
      { instruction: 'Add 1 cup water and 2 tbsp soy sauce. Add noodles, simmer 3 minutes until noodles absorb the sauce.', timer: 180 },
      { instruction: 'Toss until sauce is mostly absorbed and "ants" (pork) cling to the "tree" (noodles). Serve hot.', timer: 30 },
    ],
  },
  {
    id: 'oyster-lettuce',
    name: 'Lettuce in Oyster Sauce',
    names: { 'zh-CN': '蚝油生菜', 'zh-TW': '蠔油生菜' },
    aliases: ['蚝油生菜', 'oyster lettuce', '白灼生菜', '粤菜'],
    tags: ['家常', '小红书', '健康'],
    meal: ['lunch', 'dinner'],
    time: 'quick',
    difficulty: 'easy',
    diet: ['none', 'vegetarian', 'vegan', 'gluten-free', 'low-carb'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['lettuce', 'garlic', 'soy sauce', 'sugar', 'olive oil'],
    optional: ['ginger'],
    steps: [
      { instruction: 'Separate lettuce leaves and wash thoroughly. Mince 3 cloves garlic.', timer: 120 },
      { instruction: 'Bring a pot of water to a boil with a pinch of salt and 1 tsp oil.', timer: 300 },
      { instruction: 'Blanch lettuce 30–45 seconds until bright green and just wilted. Drain and arrange on a plate.', timer: 45 },
      { instruction: 'Heat 1 tbsp oil in a small pan. Sauté garlic until golden, about 20 seconds.', timer: 20 },
      { instruction: 'Add 2 tbsp oyster sauce (or extra soy sauce), 1 tsp sugar, and 2 tbsp water. Simmer 30 seconds.', timer: 30 },
      { instruction: 'Pour hot sauce over lettuce and serve immediately.', timer: null },
    ],
  },
  {
    id: 'dry-fried-green-beans',
    name: 'Dry-Fried Green Beans',
    names: { 'zh-CN': '干煸四季豆', 'zh-TW': '乾煸四季豆' },
    aliases: ['干煸豆角', 'dry fried beans', '四季豆', '川菜'],
    tags: ['家常', '小红书', '川菜'],
    meal: ['lunch', 'dinner'],
    time: 'medium',
    difficulty: 'medium',
    diet: ['none', 'vegetarian', 'vegan'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['green beans', 'pork', 'garlic', 'chili', 'soy sauce', 'olive oil'],
    optional: ['ginger'],
    steps: [
      { instruction: 'Trim green beans and pat completely dry — moisture causes splattering. Mince pork, garlic, and chili.', timer: 180 },
      { instruction: 'Heat 3 tbsp oil in a wok over medium-high. Fry green beans until skin blisters and wrinkled, about 6 minutes.', timer: 360 },
      { instruction: 'Remove beans. In same wok, brown minced pork until crispy.', timer: 120 },
      { instruction: 'Add garlic and chili, stir 15 seconds until fragrant.', timer: 15 },
      { instruction: 'Return green beans. Add 1 tbsp soy sauce, toss on high heat 1 minute.', timer: 60 },
      { instruction: 'Beans should be tender inside with slightly charred skin. Serve with rice.', timer: null },
    ],
  },
  {
    id: 'tomato-egg-noodles',
    name: 'Tomato Egg Noodles',
    names: { 'zh-CN': '番茄鸡蛋面', 'zh-TW': '番茄雞蛋麵' },
    aliases: ['西红柿鸡蛋面', 'tomato egg noodles', '汤面', '治愈系'],
    tags: ['家常', '小红书', '快手'],
    meal: ['lunch', 'dinner', 'breakfast'],
    time: 'quick',
    difficulty: 'easy',
    diet: ['none', 'vegetarian'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['noodles', 'tomato', 'eggs', 'onion', 'garlic', 'soy sauce', 'sugar', 'olive oil'],
    optional: ['cilantro'],
    steps: [
      { instruction: 'Dice tomatoes and onion. Beat 2 eggs. Mince garlic.', timer: 180 },
      { instruction: 'Heat 2 tbsp oil, scramble eggs until just set, break into pieces, and set aside.', timer: 90 },
      { instruction: 'Add onion and garlic, stir 30 seconds. Add tomatoes, 1 tsp sugar, cook until saucy, about 4 minutes.', timer: 240 },
      { instruction: 'Add 2 cups water and 1 tbsp soy sauce. Bring to a boil.', timer: 180 },
      { instruction: 'Add noodles, cook until done according to package. Return eggs in the last minute.', timer: 360 },
      { instruction: 'Taste and adjust seasoning. Serve hot in bowls.', timer: null },
    ],
  },
  {
    id: 'hot-sour-soup',
    name: 'Hot and Sour Soup',
    names: { 'zh-CN': '酸辣汤', 'zh-TW': '酸辣湯' },
    aliases: ['酸辣汤', 'hot sour soup', '开胃汤', '中式汤'],
    tags: ['家常', '小红书'],
    meal: ['lunch', 'dinner'],
    time: 'quick',
    difficulty: 'easy',
    diet: ['none'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['tofu', 'mushroom', 'eggs', 'vinegar', 'soy sauce', 'chili', 'ginger', 'olive oil'],
    optional: ['carrot', 'onion'],
    steps: [
      { instruction: 'Slice tofu and mushrooms into thin strips. Beat 1 egg. Mince ginger.', timer: 180 },
      { instruction: 'Bring 4 cups water to a boil with ginger and 1 tbsp soy sauce.', timer: 300 },
      { instruction: 'Add tofu and mushrooms. Simmer 3 minutes.', timer: 180 },
      { instruction: 'Stir in 3 tbsp vinegar and white pepper (or chili) to taste.', timer: null },
      { instruction: 'Drizzle beaten egg in a thin stream while stirring gently to form silky ribbons.', timer: 30 },
      { instruction: 'Adjust sourness and heat. Serve immediately.', timer: null },
    ],
  },

  // ── Western favorites ───────────────────────────────────────────────────

  {
    id: 'carbonara',
    name: 'Spaghetti Carbonara',
    names: { 'zh-CN': '卡博纳拉意大利面', 'zh-TW': '卡博納拉義大利麵' },
    aliases: ['carbonara', '培根蛋面', '意大利面', '罗马面'],
    tags: ['西式', 'comfort'],
    meal: ['lunch', 'dinner'],
    time: 'quick',
    difficulty: 'medium',
    diet: ['none'],
    cuisine: 'western',
    servings: 2,
    ingredients: ['pasta', 'bacon', 'eggs', 'cheese', 'garlic', 'olive oil'],
    optional: ['chili'],
    steps: [
      { instruction: 'Bring salted water to a boil. Cook spaghetti until al dente. Reserve 1 cup pasta water.', timer: 600 },
      { instruction: 'While pasta cooks, dice bacon and mince 1 clove garlic. Beat 2 eggs with ½ cup grated cheese.', timer: 120 },
      { instruction: 'Cook bacon in a pan over medium heat until crispy, about 5 minutes. Add garlic, stir 15 seconds.', timer: 315 },
      { instruction: 'Remove pan from heat — this is crucial. Add drained hot pasta to the pan.', timer: null },
      { instruction: 'Pour egg-cheese mixture over pasta, tossing quickly. Add pasta water splash by splash until creamy.', timer: 60 },
      { instruction: 'Season generously with black pepper. Serve immediately — do not reheat.', timer: null },
    ],
  },
  {
    id: 'caprese-salad',
    name: 'Caprese Salad',
    names: { 'zh-CN': '卡布里沙拉', 'zh-TW': '卡布里沙拉' },
    aliases: ['caprese', '番茄-mozzarella', '意式沙拉', '清爽沙拉'],
    tags: ['西式', '健康', '免火'],
    meal: ['lunch', 'dinner', 'snack'],
    time: 'quick',
    difficulty: 'easy',
    diet: ['none', 'vegetarian', 'gluten-free', 'low-carb'],
    cuisine: 'mediterranean',
    servings: 2,
    ingredients: ['tomato', 'cheese', 'basil', 'olive oil'],
    optional: ['onion'],
    steps: [
      { instruction: 'Slice ripe tomatoes and fresh mozzarella (or cheese) into ½ cm rounds.', timer: 180 },
      { instruction: 'Arrange tomato and cheese slices alternately on a plate, overlapping slightly.', timer: 60 },
      { instruction: 'Tuck fresh basil leaves between slices.', timer: null },
      { instruction: 'Drizzle with 2 tbsp extra virgin olive oil.', timer: null },
      { instruction: 'Season with flaky salt and black pepper. Rest 5 minutes before serving.', timer: 300 },
    ],
  },
  {
    id: 'honey-garlic-chicken',
    name: 'Honey Garlic Chicken',
    names: { 'zh-CN': '蜂蜜蒜香鸡', 'zh-TW': '蜂蜜蒜香雞' },
    aliases: ['蜜汁鸡', 'honey chicken', '蒜香鸡', '西式鸡'],
    tags: ['西式', '小红书', '快手'],
    meal: ['lunch', 'dinner'],
    time: 'quick',
    difficulty: 'easy',
    diet: ['none', 'gluten-free'],
    cuisine: 'western',
    servings: 2,
    ingredients: ['chicken', 'garlic', 'soy sauce', 'sugar', 'olive oil'],
    optional: ['ginger', 'chili'],
    steps: [
      { instruction: 'Cut chicken into bite-sized pieces. Pat dry. Mince 4 cloves garlic.', timer: 180 },
      { instruction: 'Mix sauce: 3 tbsp honey (or sugar), 2 tbsp soy sauce, and 2 tbsp water.', timer: null },
      { instruction: 'Heat 2 tbsp oil in a pan over medium-high. Sear chicken until golden, about 4 minutes per side.', timer: 480 },
      { instruction: 'Add garlic, stir 30 seconds until fragrant.', timer: 30 },
      { instruction: 'Pour in sauce. Simmer 3–4 minutes, turning chicken, until glaze is thick and sticky.', timer: 240 },
      { instruction: 'Serve over rice or with vegetables.', timer: null },
    ],
  },
  {
    id: 'teriyaki-chicken-bowl',
    name: 'Teriyaki Chicken Bowl',
    names: { 'zh-CN': '照烧鸡肉饭', 'zh-TW': '照燒雞肉飯' },
    aliases: ['照烧饭', 'teriyaki bowl', '日式鸡肉饭', '盖饭'],
    tags: ['亚洲', '小红书', 'bowl'],
    meal: ['lunch', 'dinner'],
    time: 'quick',
    difficulty: 'easy',
    diet: ['none'],
    cuisine: 'asian',
    servings: 2,
    ingredients: ['chicken', 'rice', 'soy sauce', 'sugar', 'garlic', 'ginger', 'olive oil'],
    optional: ['broccoli', 'carrot'],
    steps: [
      { instruction: 'Cook rice according to package or rice cooker. Slice chicken into strips.', timer: 1200 },
      { instruction: 'Mix teriyaki sauce: 3 tbsp soy sauce, 2 tbsp sugar, 1 minced garlic clove, and 1 tsp ginger.', timer: 60 },
      { instruction: 'Heat 1 tbsp oil in a pan over medium-high. Cook chicken until done, about 5 minutes.', timer: 300 },
      { instruction: 'Pour teriyaki sauce over chicken. Simmer 2 minutes until glossy and caramelized.', timer: 120 },
      { instruction: 'Steam or stir-fry broccoli and carrot if using, about 3 minutes.', timer: 180 },
      { instruction: 'Serve chicken and vegetables over rice. Drizzle remaining pan sauce.', timer: null },
    ],
  },
  {
    id: 'french-toast',
    name: 'French Toast',
    names: { 'zh-CN': '法式吐司', 'zh-TW': '法式吐司' },
    aliases: ['西多士', 'french toast', '早餐吐司', '甜吐司'],
    tags: ['早餐', '西式', '快手'],
    meal: ['breakfast', 'snack'],
    time: 'quick',
    difficulty: 'easy',
    diet: ['none', 'vegetarian'],
    cuisine: 'western',
    servings: 2,
    ingredients: ['bread', 'eggs', 'milk', 'butter', 'sugar'],
    optional: ['cinnamon'],
    steps: [
      { instruction: 'Whisk 2 eggs with ¼ cup milk, 1 tbsp sugar, and a pinch of cinnamon if using.', timer: 60 },
      { instruction: 'Cut bread into thick slices. Soak each slice in egg mixture 20 seconds per side.', timer: 60 },
      { instruction: 'Heat 1 tbsp butter in a pan over medium heat until foaming.', timer: 30 },
      { instruction: 'Cook soaked bread 2–3 minutes per side until golden brown and cooked through.', timer: 360 },
      { instruction: 'Serve immediately with maple syrup, fruit, or powdered sugar.', timer: null },
    ],
  },
  {
    id: 'mushroom-risotto',
    name: 'Simple Mushroom Risotto',
    names: { 'zh-CN': '蘑菇意式烩饭', 'zh-TW': '蘑菇義式燉飯' },
    aliases: ['蘑菇烩饭', 'mushroom risotto', '意式饭', '奶油蘑菇饭'],
    tags: ['西式', 'comfort'],
    meal: ['lunch', 'dinner'],
    time: 'medium',
    difficulty: 'medium',
    diet: ['none', 'vegetarian'],
    cuisine: 'western',
    servings: 2,
    ingredients: ['rice', 'mushroom', 'onion', 'garlic', 'butter', 'cheese', 'olive oil'],
    optional: ['basil'],
    steps: [
      { instruction: 'Slice mushrooms and dice onion. Mince garlic. Warm 3 cups broth or water in a separate pot.', timer: 180 },
      { instruction: 'Melt 2 tbsp butter with 1 tbsp oil in a pan. Sauté mushrooms until golden, about 5 minutes. Set aside.', timer: 300 },
      { instruction: 'In same pan, cook onion until soft. Add garlic, stir 30 seconds. Add 1 cup arborio or short-grain rice, toast 1 minute.', timer: 90 },
      { instruction: 'Add warm broth one ladle at a time, stirring until absorbed before adding more. Repeat for 18–20 minutes.', timer: 1200 },
      { instruction: 'When rice is creamy and al dente, fold in mushrooms, 2 tbsp butter, and ¼ cup grated cheese.', timer: 60 },
      { instruction: 'Season with salt and pepper. Serve immediately.', timer: null },
    ],
  },
  {
    id: 'bbq-glazed-chicken',
    name: 'BBQ Glazed Chicken',
    names: { 'zh-CN': 'BBQ蜜汁烤鸡', 'zh-TW': 'BBQ蜜汁烤雞' },
    aliases: ['烤鸡', 'bbq chicken', '蜜汁烤鸡', '美式烤鸡'],
    tags: ['西式', '小红书', '烤箱'],
    meal: ['lunch', 'dinner'],
    time: 'medium',
    difficulty: 'easy',
    diet: ['none', 'gluten-free'],
    cuisine: 'western',
    servings: 2,
    ingredients: ['chicken', 'soy sauce', 'sugar', 'garlic', 'olive oil'],
    optional: ['chili', 'ginger'],
    steps: [
      { instruction: 'Pat chicken dry. Mix glaze: 3 tbsp ketchup (or tomato paste), 2 tbsp soy sauce, 2 tbsp sugar, 2 minced garlic cloves.', timer: 120 },
      { instruction: 'Coat chicken with half the glaze. Marinate at least 15 minutes (or up to overnight).', timer: 900 },
      { instruction: 'Preheat oven to 200°C (400°F) or heat grill to medium-high.', timer: 600 },
      { instruction: 'Roast or grill chicken 20 minutes, turning once halfway.', timer: 1200 },
      { instruction: 'Brush with remaining glaze in the last 5 minutes until sticky and caramelized.', timer: 300 },
      { instruction: 'Rest 5 minutes before serving. Check internal temperature reaches 74°C (165°F).', timer: 300 },
    ],
  },

  ...WORLD_RECIPES,
  ...WORLD_RECIPES_2,
  ...CHINA_RECIPES,
];
